server:
  port: 8889


spring:
  application:
    name: book-store

  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: root
    test-while-idle: true
    validation-query: SELECT 1
    max-wait: 20000
    max-active: 300
    test-on-borrow: true
    platform: mysql
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/bookstore?useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
      maximum-pool-size: 400
      idle-timeout: 50000
      max-lifetime: 2400000
      connection-timeout: 60000
      pool-name: mysqlHikariCP
      minimum-idle: 10
#

  jpa:
    #optional - show SQL statements in console.
    show-sql: true
    properties:
      javax:
        cache:
          uri: classpath:ehcache.xml
        persistence:
          sharedCache:
            #required - enable selective caching mode - only entities using @Cacheable annotation will use L2 cache.
            mode: ENABLE_SELECTIVE
      hibernate:
        #optional - enable SQL statements formatting.
        format_sql: true
        #optional - generate statistics to check if L2/query cache is actually being used.
        generate_statistics: true
        cache:
          #required - turn on L2 cache.
          use_second_level_cache: true
          #optional - turn on query cache.
          use_query_cache: true
          region:
            #required - classpath to cache region factory.
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  cache:
    ehcache:
      config: classpath:ehcache.xml
    type: ehcache
    cache-names: demoBook



logging:
  level:
    #root: TRACE
    org.hibernate.stat: DEBUG
    org.hibernate.type: TRACE
    net.sf.ehcache: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka
  instance:
    preferIpAddress: true

